# Generated by Django 4.1 on 2022-09-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='useremail',
        ),
    ]
