# Generated by Django 4.1 on 2022-09-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0003_rename_login_modellogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelLogin',
        ),
    ]
